services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  django:
    build: ./django
    command: sh -c "./wait-for-it.sh db:5432 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django:/django
    ports:
      - 8000:8000
    depends_on:
      - db
  reactjs:
    build: ./reactjs
    command: sh -c "npm run dev"
    ports:
      - 5173:5173
    volumes:
      - ./reactjs:/reactjs
      - reactjs_node_modules:/reactjs/node_modules
volumes:
  reactjs_node_modules:
